load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "spd_reader",
    srcs = ["spd_reader.cc"],
    hdrs = ["spd_reader.h"],
)
